name: 'React App Build and Test'

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  react:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
      - uses: actions/checkout@v3

      - name: Install dependancies
      - run: cd client && npm install

      - name: Build app
      - run: cd client && npm run build

      # - name: Test application
      # - run: cd client && npm test
